#!/usr/bin/env python3
"""Generate the api-sync status block in docs/api-sync/README.md.

The README's status numbers were previously hand-maintained, and they rotted:
they claimed "317 / 317 spec operations covered (100%)" while the SDK had 57
unimplemented operations and one mis-homed path. This script derives the block
from the checkers themselves, so it cannot disagree with reality.

All numbers are measured against the COMMITTED BASELINE
(.github/cache/samsara-api-baseline.json) -- the spec the SDK has actually been
reconciled against. Live-spec drift is the daily workflow's job, not the
README's.

Modes:
  --stdout   print the block (default)
  --write    rewrite the block in place between the sync-status markers
  --check    exit 1 if the file's block differs from the freshly rendered one
"""

from __future__ import annotations

import argparse
import contextlib
import importlib.util
import io
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOLS = REPO_ROOT / "tools"
BASELINE = REPO_ROOT / ".github" / "cache" / "samsara-api-baseline.json"
README = REPO_ROOT / "docs" / "api-sync" / "README.md"

START = "<!-- sync-status:start (generated by tools/render-sync-status.py — do not edit) -->"
END = "<!-- sync-status:end -->"


def _load(name: str, filename: str):
    path = TOOLS / filename
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render() -> str:
    if not BASELINE.exists():
        raise SystemExit(f"ERROR: baseline not found at {BASELINE}")

    spec = json.loads(BASELINE.read_text())

    cs = _load("check_sdk_sync", "check-sdk-sync.py")
    fab = _load("check_sdk_fabrication", "check-sdk-fabrication.py")
    cms = _load("check_model_sync", "check-model-sync.py")
    api = _load("check_api_sync", "check-api-sync.py")

    fp = api.content_fingerprint(spec)

    ops, eps, matched, mismatched, unresolved, _by_tag, missing = cs.analyze(spec)
    _o, _e, duplicates, tag_drift, _b = fab.analyze(cs, spec)

    # check-model-sync prints as a side effect; keep stdout clean.
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        findings, _examined, _n = cms.analyze(spec)
    active, allowlisted = cms.split_allowlisted(cms.dedup(findings))

    # dedup() yields plain dicts, not Finding objects.
    sev = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    weak_bodies = set()
    for f in active:
        key = f.get("severity") or "LOW"
        sev[key] = sev.get(key, 0) + 1
        if f.get("ftype") == "weak-typing" and f.get("prop") in ("<request>", "<response>"):
            weak_bodies.add(f.get("sdk_type", ""))

    covered = len(ops) - len(missing)
    pct = (covered / len(ops) * 100) if ops else 0.0

    # NOTHING in this block may derive from mutable git state (HEAD sha, commit
    # dates). The block is committed, so any such value is stale the moment the
    # commit lands and `--check` could never pass again — and CI checks out with
    # fetch-depth 1, where `git log` on a single file yields nothing anyway.
    # Every line below is a pure function of the baseline spec and the SDK source.
    lines = [
        START,
        f"> **Baseline spec**: `{spec.get('info', {}).get('version', '?')}`, content hash "
        f"`{fp['hash']}`, {fp['ops']} operations, {fp['schemas']} schemas "
        f"(`.github/cache/samsara-api-baseline.json`)",
        f"> **Endpoint coverage**: {covered} / {len(ops)} spec operations implemented "
        f"({pct:.1f}%) · {len(mismatched)} mismatched · {len(unresolved)} unresolved · "
        f"{len(eps)} SDK endpoints parsed",
        f"> **Fabrication**: {len(duplicates)} duplicate-coverage · {len(tag_drift)} client↔tag drift",
        f"> **Model parity**: {sev['CRITICAL']} CRITICAL · {sev['HIGH']} HIGH · "
        f"{sev['MEDIUM']} MEDIUM · {sev['LOW']} LOW active · {len(allowlisted)} allowlisted "
        f"(each with a spec pointer)",
        f"> **Weak-typed endpoint bodies**: {len(weak_bodies)} (whole-body `object` request/response)",
        "> _Generated — run `python3 tools/render-sync-status.py --write` after any change "
        "that moves these numbers._",
        END,
    ]
    return "\n".join(lines)


def _splice(text: str, block: str) -> str:
    if START not in text or END not in text:
        raise SystemExit(
            f"ERROR: {README} is missing the sync-status markers.\n"
            f"Add these two lines where the status block should go:\n{START}\n{END}"
        )
    head = text.split(START)[0]
    tail = text.split(END, 1)[1]
    return head + block + tail


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite the block in the README")
    mode.add_argument("--check", action="store_true", help="exit 1 if the README block is stale")
    mode.add_argument("--stdout", action="store_true", help="print the block (default)")
    args = ap.parse_args()

    block = render()

    if args.write:
        text = README.read_text()
        README.write_text(_splice(text, block))
        print(f"Status block written to {README.relative_to(REPO_ROOT)}")
        return

    if args.check:
        text = README.read_text()
        if START not in text or END not in text:
            print(f"FAIL: {README} is missing the sync-status markers.", file=sys.stderr)
            sys.exit(1)
        current = START + text.split(START, 1)[1].split(END, 1)[0] + END
        if current.strip() != block.strip():
            print(
                "FAIL: the api-sync status block in docs/api-sync/README.md is stale.\n"
                "Run: python3 tools/render-sync-status.py --write\n",
                file=sys.stderr,
            )
            print("--- expected ---", file=sys.stderr)
            print(block, file=sys.stderr)
            sys.exit(1)
        print("Status block is up to date.")
        return

    print(block)


if __name__ == "__main__":
    main()
